# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutControls = QtWidgets.QVBoxLayout()
        self.verticalLayoutControls.setObjectName("verticalLayoutControls")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayoutControls.addWidget(self.label_5)
        self.turretMode = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turretMode.sizePolicy().hasHeightForWidth())
        self.turretMode.setSizePolicy(sizePolicy)
        self.turretMode.setObjectName("turretMode")
        self.manual = QtWidgets.QWidget()
        self.manual.setObjectName("manual")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.manual)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_55 = QtWidgets.QLabel(self.manual)
        self.label_55.setObjectName("label_55")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.speedMode = QtWidgets.QComboBox(self.manual)
        self.speedMode.setObjectName("speedMode")
        self.speedMode.addItem("")
        self.speedMode.addItem("")
        self.speedMode.addItem("")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speedMode)
        self.verticalLayout.addLayout(self.formLayout_10)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.turretMode.addTab(self.manual, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.manualOverride = QtWidgets.QCheckBox(self.tab_2)
        self.manualOverride.setObjectName("manualOverride")
        self.horizontalLayout_3.addWidget(self.manualOverride)
        self.cameraCalibrateButton = QtWidgets.QPushButton(self.tab_2)
        self.cameraCalibrateButton.setObjectName("cameraCalibrateButton")
        self.horizontalLayout_3.addWidget(self.cameraCalibrateButton)
        self.verticalLayout_15.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_5.addWidget(self.label_51)
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_5.addWidget(self.label_38)
        self.label_52 = QtWidgets.QLabel(self.tab_2)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_5.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_5.addWidget(self.label_53)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 0, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 0, 8, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 0, 6, 1, 1)
        self.verticalSlider_7 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_7.setMaximum(180)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.gridLayout.addWidget(self.verticalSlider_7, 1, 6, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 0, 11, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 0, 3, 1, 1)
        self.verticalSlider_4 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_4.setMaximum(180)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.gridLayout.addWidget(self.verticalSlider_4, 1, 3, 1, 1)
        self.verticalSlider_9 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_9.setMaximum(255)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.gridLayout.addWidget(self.verticalSlider_9, 1, 8, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 0, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 0, 9, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 0, 5, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 0, 4, 1, 1)
        self.verticalSlider_10 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_10.setMaximum(180)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.gridLayout.addWidget(self.verticalSlider_10, 1, 9, 1, 1)
        self.verticalSlider_12 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_12.setMaximum(255)
        self.verticalSlider_12.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_12.setObjectName("verticalSlider_12")
        self.gridLayout.addWidget(self.verticalSlider_12, 1, 11, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_3.setMaximum(255)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.gridLayout.addWidget(self.verticalSlider_3, 1, 2, 1, 1)
        self.verticalSlider_6 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_6.setMaximum(255)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.gridLayout.addWidget(self.verticalSlider_6, 1, 5, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_2.setMaximum(255)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.gridLayout.addWidget(self.verticalSlider_2, 1, 1, 1, 1)
        self.verticalSlider_11 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_11.setMaximum(255)
        self.verticalSlider_11.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_11.setObjectName("verticalSlider_11")
        self.gridLayout.addWidget(self.verticalSlider_11, 1, 10, 1, 1)
        self.verticalSlider_5 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_5.setMaximum(255)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.gridLayout.addWidget(self.verticalSlider_5, 1, 4, 1, 1)
        self.verticalSlider_8 = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider_8.setMaximum(255)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.gridLayout.addWidget(self.verticalSlider_8, 1, 7, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 0, 7, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 0, 10, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(self.tab_2)
        self.verticalSlider.setMaximum(180)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout.addWidget(self.verticalSlider, 1, 0, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_15)
        self.turretMode.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 340, 502))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.manualOverride_1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.manualOverride_1.setObjectName("manualOverride_1")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.manualOverride_1)
        self.latInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.latInput.setText("")
        self.latInput.setObjectName("latInput")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.latInput)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lonInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lonInput.setText("")
        self.lonInput.setObjectName("lonInput")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lonInput)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_57.setObjectName("label_57")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.altinput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.altinput.setText("")
        self.altinput.setObjectName("altinput")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.altinput)
        self.verticalLayout_14.addLayout(self.formLayout_5)
        self.skyMode = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        self.skyMode.setObjectName("skyMode")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setObjectName("label_22")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.timeMode = QtWidgets.QComboBox(self.tab_4)
        self.timeMode.setObjectName("timeMode")
        self.timeMode.addItem("")
        self.timeMode.addItem("")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeMode)
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setObjectName("label_29")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_4)
        self.timeEdit.setEnabled(False)
        self.timeEdit.setAccelerated(True)
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.starInput = QtWidgets.QLineEdit(self.tab_4)
        self.starInput.setObjectName("starInput")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.starInput)
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.verticalLayout_11.addLayout(self.formLayout_6)
        self.starList = QtWidgets.QListView(self.tab_4)
        self.starList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.starList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.starList.setObjectName("starList")
        self.verticalLayout_11.addWidget(self.starList)
        self.skyMode.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.timeMode_1 = QtWidgets.QComboBox(self.tab_5)
        self.timeMode_1.setObjectName("timeMode_1")
        self.timeMode_1.addItem("")
        self.timeMode_1.addItem("")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeMode_1)
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.timeEdit_1 = QtWidgets.QTimeEdit(self.tab_5)
        self.timeEdit_1.setEnabled(False)
        self.timeEdit_1.setAccelerated(True)
        self.timeEdit_1.setObjectName("timeEdit_1")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit_1)
        self.label_56 = QtWidgets.QLabel(self.tab_5)
        self.label_56.setObjectName("label_56")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.objectInput = QtWidgets.QLineEdit(self.tab_5)
        self.objectInput.setObjectName("objectInput")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.objectInput)
        self.verticalLayout_12.addLayout(self.formLayout_7)
        self.objectList = QtWidgets.QListView(self.tab_5)
        self.objectList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.objectList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.objectList.setObjectName("objectList")
        self.verticalLayout_12.addWidget(self.objectList)
        self.skyMode.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.timeMode_2 = QtWidgets.QComboBox(self.tab_6)
        self.timeMode_2.setObjectName("timeMode_2")
        self.timeMode_2.addItem("")
        self.timeMode_2.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeMode_2)
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_6)
        self.timeEdit_2.setEnabled(False)
        self.timeEdit_2.setReadOnly(False)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit_2)
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setObjectName("label_37")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.satelliteInput = QtWidgets.QLineEdit(self.tab_6)
        self.satelliteInput.setText("")
        self.satelliteInput.setObjectName("satelliteInput")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.satelliteInput)
        self.verticalLayout_10.addLayout(self.formLayout_4)
        self.satelliteList = QtWidgets.QListView(self.tab_6)
        self.satelliteList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.satelliteList.setObjectName("satelliteList")
        self.verticalLayout_10.addWidget(self.satelliteList)
        self.skyMode.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.callsignInput = QtWidgets.QLineEdit(self.tab_7)
        self.callsignInput.setObjectName("callsignInput")
        self.horizontalLayout_4.addWidget(self.callsignInput)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.airTrafficList = QtWidgets.QListView(self.tab_7)
        self.airTrafficList.setMinimumSize(QtCore.QSize(0, 100))
        self.airTrafficList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.airTrafficList.setObjectName("airTrafficList")
        self.verticalLayout_13.addWidget(self.airTrafficList)
        self.refreshButton = QtWidgets.QPushButton(self.tab_7)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout_13.addWidget(self.refreshButton)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_32 = QtWidgets.QLabel(self.tab_7)
        self.label_32.setObjectName("label_32")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.minLat = QtWidgets.QLineEdit(self.tab_7)
        self.minLat.setText("")
        self.minLat.setObjectName("minLat")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.minLat)
        self.label_33 = QtWidgets.QLabel(self.tab_7)
        self.label_33.setObjectName("label_33")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.minLon = QtWidgets.QLineEdit(self.tab_7)
        self.minLon.setText("")
        self.minLon.setObjectName("minLon")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minLon)
        self.label_34 = QtWidgets.QLabel(self.tab_7)
        self.label_34.setObjectName("label_34")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.maxLat = QtWidgets.QLineEdit(self.tab_7)
        self.maxLat.setText("")
        self.maxLat.setObjectName("maxLat")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxLat)
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setObjectName("label_35")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.maxLon = QtWidgets.QLineEdit(self.tab_7)
        self.maxLon.setText("")
        self.maxLon.setObjectName("maxLon")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxLon)
        self.verticalLayout_13.addLayout(self.formLayout_8)
        self.skyMode.addTab(self.tab_7, "")
        self.verticalLayout_14.addWidget(self.skyMode)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        self.turretMode.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.manualOverride_2 = QtWidgets.QCheckBox(self.tab)
        self.manualOverride_2.setObjectName("manualOverride_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.manualOverride_2)
        self.label_54 = QtWidgets.QLabel(self.tab)
        self.label_54.setObjectName("label_54")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.mosquitoSize = QtWidgets.QDoubleSpinBox(self.tab)
        self.mosquitoSize.setAccelerated(True)
        self.mosquitoSize.setObjectName("mosquitoSize")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mosquitoSize)
        self.verticalLayout_9.addLayout(self.formLayout)
        self.turretMode.addTab(self.tab, "")
        self.verticalLayoutControls.addWidget(self.turretMode)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setObjectName("updateButton")
        self.verticalLayoutControls.addWidget(self.updateButton)
        self.horizontalLayout.addLayout(self.verticalLayoutControls)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayoutActions = QtWidgets.QVBoxLayout()
        self.verticalLayoutActions.setObjectName("verticalLayoutActions")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutActions.addWidget(self.label_6)
        self.calibrateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calibrateButton.setObjectName("calibrateButton")
        self.verticalLayoutActions.addWidget(self.calibrateButton)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayoutActions.addWidget(self.homeButton)
        self.fireButton = QtWidgets.QPushButton(self.centralwidget)
        self.fireButton.setObjectName("fireButton")
        self.verticalLayoutActions.addWidget(self.fireButton)
        self.powerOffButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerOffButton.setObjectName("powerOffButton")
        self.verticalLayoutActions.addWidget(self.powerOffButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(235, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.stopButton.setPalette(palette)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayoutActions.addWidget(self.stopButton)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayoutActions.addWidget(self.line_5)
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.verticalLayoutActions.addWidget(self.label_59)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setObjectName("label_58")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setObjectName("label_60")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.altTarget = QtWidgets.QLineEdit(self.centralwidget)
        self.altTarget.setObjectName("altTarget")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.altTarget)
        self.azTarget = QtWidgets.QLineEdit(self.centralwidget)
        self.azTarget.setObjectName("azTarget")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.azTarget)
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        self.label_64.setObjectName("label_64")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.distanceTarget = QtWidgets.QLineEdit(self.centralwidget)
        self.distanceTarget.setReadOnly(True)
        self.distanceTarget.setObjectName("distanceTarget")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.distanceTarget)
        self.verticalLayoutActions.addLayout(self.formLayout_3)
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.verticalLayoutActions.addWidget(self.label_63)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setObjectName("label_61")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.altActual = QtWidgets.QLineEdit(self.centralwidget)
        self.altActual.setReadOnly(True)
        self.altActual.setObjectName("altActual")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.altActual)
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setObjectName("label_62")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.azActual = QtWidgets.QLineEdit(self.centralwidget)
        self.azActual.setReadOnly(True)
        self.azActual.setObjectName("azActual")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.azActual)
        self.verticalLayoutActions.addLayout(self.formLayout_9)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutActions.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayoutActions)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayoutSettings = QtWidgets.QVBoxLayout()
        self.verticalLayoutSettings.setObjectName("verticalLayoutSettings")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayoutSettings.addWidget(self.label_8)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setEnabled(True)
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_8)
        self.scrollArea.setMinimumSize(QtCore.QSize(261, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 560))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.STEP_MODE = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.STEP_MODE.setObjectName("STEP_MODE")
        self.STEP_MODE.addItem("")
        self.STEP_MODE.addItem("")
        self.STEP_MODE.addItem("")
        self.STEP_MODE.addItem("")
        self.STEP_MODE.addItem("")
        self.STEP_MODE.addItem("")
        self.STEP_MODE.addItem("")
        self.STEP_MODE.addItem("")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.STEP_MODE)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.OC_SD = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.OC_SD.setObjectName("OC_SD")
        self.OC_SD.addItem("")
        self.OC_SD.addItem("")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.OC_SD)
        self.SW_MODE = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.SW_MODE.setObjectName("SW_MODE")
        self.SW_MODE.addItem("")
        self.SW_MODE.addItem("")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.SW_MODE)
        self.OCD_TH = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.OCD_TH.setAccelerated(True)
        self.OCD_TH.setDecimals(3)
        self.OCD_TH.setMinimum(0.375)
        self.OCD_TH.setMaximum(6.0)
        self.OCD_TH.setSingleStep(0.375)
        self.OCD_TH.setProperty("value", 3.375)
        self.OCD_TH.setObjectName("OCD_TH")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.OCD_TH)
        self.STALL_TH = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.STALL_TH.setAccelerated(True)
        self.STALL_TH.setDecimals(5)
        self.STALL_TH.setMinimum(0.03125)
        self.STALL_TH.setMaximum(4.0)
        self.STALL_TH.setSingleStep(0.03125)
        self.STALL_TH.setProperty("value", 2.03125)
        self.STALL_TH.setObjectName("STALL_TH")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.STALL_TH)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.POW_SR = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.POW_SR.setObjectName("POW_SR")
        self.POW_SR.addItem("")
        self.POW_SR.addItem("")
        self.POW_SR.addItem("")
        self.POW_SR.addItem("")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.POW_SR)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.OSC_SEL = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.OSC_SEL.setObjectName("OSC_SEL")
        self.OSC_SEL.addItem("")
        self.OSC_SEL.addItem("")
        self.OSC_SEL.addItem("")
        self.OSC_SEL.addItem("")
        self.OSC_SEL.addItem("")
        self.OSC_SEL.addItem("")
        self.OSC_SEL.addItem("")
        self.OSC_SEL.addItem("")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.OSC_SEL)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.EXT_CLK = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.EXT_CLK.setObjectName("EXT_CLK")
        self.EXT_CLK.addItem("")
        self.EXT_CLK.addItem("")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.EXT_CLK)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.EN_VSCOMP = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.EN_VSCOMP.setObjectName("EN_VSCOMP")
        self.EN_VSCOMP.addItem("")
        self.EN_VSCOMP.addItem("")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.EN_VSCOMP)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.F_PWM_DEC = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.F_PWM_DEC.setObjectName("F_PWM_DEC")
        self.F_PWM_DEC.addItem("")
        self.F_PWM_DEC.addItem("")
        self.F_PWM_DEC.addItem("")
        self.F_PWM_DEC.addItem("")
        self.F_PWM_DEC.addItem("")
        self.F_PWM_DEC.addItem("")
        self.F_PWM_DEC.addItem("")
        self.F_PWM_DEC.addItem("")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.F_PWM_DEC)
        self.F_PWM_INT = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.F_PWM_INT.setObjectName("F_PWM_INT")
        self.F_PWM_INT.addItem("")
        self.F_PWM_INT.addItem("")
        self.F_PWM_INT.addItem("")
        self.F_PWM_INT.addItem("")
        self.F_PWM_INT.addItem("")
        self.F_PWM_INT.addItem("")
        self.F_PWM_INT.addItem("")
        self.F_PWM_INT.addItem("")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.F_PWM_INT)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.ACC = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ACC.setAccelerated(True)
        self.ACC.setDecimals(2)
        self.ACC.setMinimum(14.55)
        self.ACC.setMaximum(59590.0)
        self.ACC.setSingleStep(10.0)
        self.ACC.setProperty("value", 2008.0)
        self.ACC.setObjectName("ACC")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ACC)
        self.DEC = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.DEC.setAccelerated(True)
        self.DEC.setDecimals(2)
        self.DEC.setMinimum(14.55)
        self.DEC.setMaximum(59590.0)
        self.DEC.setSingleStep(10.0)
        self.DEC.setProperty("value", 2008.0)
        self.DEC.setObjectName("DEC")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.DEC)
        self.MAX_SPEED = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.MAX_SPEED.setAccelerated(True)
        self.MAX_SPEED.setDecimals(2)
        self.MAX_SPEED.setMinimum(15.25)
        self.MAX_SPEED.setMaximum(15610.0)
        self.MAX_SPEED.setSingleStep(10.0)
        self.MAX_SPEED.setProperty("value", 991.8)
        self.MAX_SPEED.setObjectName("MAX_SPEED")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MAX_SPEED)
        self.MIN_SPEED = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.MIN_SPEED.setAccelerated(True)
        self.MIN_SPEED.setDecimals(2)
        self.MIN_SPEED.setMinimum(0.0)
        self.MIN_SPEED.setMaximum(976.3)
        self.MIN_SPEED.setSingleStep(10.0)
        self.MIN_SPEED.setProperty("value", 0.0)
        self.MIN_SPEED.setObjectName("MIN_SPEED")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MIN_SPEED)
        self.FS_SPD = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.FS_SPD.setAccelerated(True)
        self.FS_SPD.setDecimals(2)
        self.FS_SPD.setMinimum(7.63)
        self.FS_SPD.setMaximum(15625.0)
        self.FS_SPD.setSingleStep(15.25)
        self.FS_SPD.setProperty("value", 602.7)
        self.FS_SPD.setObjectName("FS_SPD")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.FS_SPD)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_10)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 259, 369))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.formLayout_11 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_3)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.doubleSpinBox_3.setAccelerated(True)
        self.doubleSpinBox_3.setProperty("value", 68.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_3)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_65.setObjectName("label_65")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.doubleSpinBox.setAccelerated(True)
        self.doubleSpinBox.setMaximum(61.73)
        self.doubleSpinBox.setSingleStep(1.928952)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_66.setObjectName("label_66")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.doubleSpinBox_2.setAccelerated(True)
        self.doubleSpinBox_2.setMaximum(246.91)
        self.doubleSpinBox_2.setSingleStep(1.928952)
        self.doubleSpinBox_2.setProperty("value", 0.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_67.setObjectName("label_67")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_67)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_68.setObjectName("label_68")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_68)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_10, "")
        self.verticalLayoutSettings.addWidget(self.tabWidget)
        self.updateSettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateSettingsButton.setObjectName("updateSettingsButton")
        self.verticalLayoutSettings.addWidget(self.updateSettingsButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.copyDeviceButton = QtWidgets.QPushButton(self.centralwidget)
        self.copyDeviceButton.setObjectName("copyDeviceButton")
        self.horizontalLayout_2.addWidget(self.copyDeviceButton)
        self.restoreDefaultsButton = QtWidgets.QPushButton(self.centralwidget)
        self.restoreDefaultsButton.setObjectName("restoreDefaultsButton")
        self.horizontalLayout_2.addWidget(self.restoreDefaultsButton)
        self.verticalLayoutSettings.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayoutSettings)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.spiCommand = QtWidgets.QLineEdit(self.centralwidget)
        self.spiCommand.setObjectName("spiCommand")
        self.horizontalLayout_6.addWidget(self.spiCommand)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_6.addWidget(self.sendButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 24))
        self.menubar.setAutoFillBackground(True)
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_Defaults = QtWidgets.QAction(MainWindow)
        self.actionSave_Defaults.setObjectName("actionSave_Defaults")
        self.actionCalibrate = QtWidgets.QAction(MainWindow)
        self.actionCalibrate.setObjectName("actionCalibrate")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionPower_Off = QtWidgets.QAction(MainWindow)
        self.actionPower_Off.setObjectName("actionPower_Off")
        self.actionForce_Stop = QtWidgets.QAction(MainWindow)
        self.actionForce_Stop.setObjectName("actionForce_Stop")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionCalibrate_2 = QtWidgets.QAction(MainWindow)
        self.actionCalibrate_2.setObjectName("actionCalibrate_2")
        self.actionHome_2 = QtWidgets.QAction(MainWindow)
        self.actionHome_2.setObjectName("actionHome_2")
        self.actionFire = QtWidgets.QAction(MainWindow)
        self.actionFire.setObjectName("actionFire")
        self.actionPower_Off_2 = QtWidgets.QAction(MainWindow)
        self.actionPower_Off_2.setObjectName("actionPower_Off_2")
        self.actionEmergency_Stop = QtWidgets.QAction(MainWindow)
        self.actionEmergency_Stop.setObjectName("actionEmergency_Stop")
        self.actionClose_Window = QtWidgets.QAction(MainWindow)
        self.actionClose_Window.setObjectName("actionClose_Window")
        self.actionReset_Defaults = QtWidgets.QAction(MainWindow)
        self.actionReset_Defaults.setObjectName("actionReset_Defaults")
        self.menuSettings.addAction(self.actionSave_Defaults)
        self.menuSettings.addAction(self.actionClose_Window)
        self.menuSettings.addAction(self.actionReset_Defaults)
        self.menuActions.addAction(self.actionCalibrate_2)
        self.menuActions.addAction(self.actionHome_2)
        self.menuActions.addAction(self.actionFire)
        self.menuActions.addAction(self.actionPower_Off_2)
        self.menuActions.addAction(self.actionEmergency_Stop)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.label_55.setBuddy(self.speedMode)
        self.label_4.setBuddy(self.lonInput)
        self.label_3.setBuddy(self.latInput)
        self.label_57.setBuddy(self.altinput)
        self.label_22.setBuddy(self.timeMode)
        self.label_29.setBuddy(self.timeEdit)
        self.label_36.setBuddy(self.starInput)
        self.label_30.setBuddy(self.timeMode_1)
        self.label_31.setBuddy(self.timeEdit_1)
        self.label_14.setBuddy(self.timeMode_2)
        self.label_13.setBuddy(self.timeEdit_2)
        self.label_37.setBuddy(self.satelliteInput)
        self.label.setBuddy(self.callsignInput)
        self.label_32.setBuddy(self.minLat)
        self.label_33.setBuddy(self.minLon)
        self.label_34.setBuddy(self.maxLat)
        self.label_35.setBuddy(self.maxLon)
        self.label_54.setBuddy(self.mosquitoSize)
        self.label_58.setBuddy(self.altTarget)
        self.label_60.setBuddy(self.azTarget)
        self.label_64.setBuddy(self.distanceTarget)
        self.label_61.setBuddy(self.altActual)
        self.label_62.setBuddy(self.azActual)
        self.label_11.setBuddy(self.MIN_SPEED)
        self.label_12.setBuddy(self.OCD_TH)
        self.label_15.setBuddy(self.STALL_TH)
        self.label_16.setBuddy(self.STEP_MODE)
        self.label_17.setBuddy(self.SW_MODE)
        self.label_18.setBuddy(self.OC_SD)
        self.label_20.setBuddy(self.POW_SR)
        self.label_24.setBuddy(self.OSC_SEL)
        self.label_25.setBuddy(self.EXT_CLK)
        self.label_21.setBuddy(self.EN_VSCOMP)
        self.label_26.setBuddy(self.F_PWM_DEC)
        self.label_27.setBuddy(self.F_PWM_INT)
        self.label_7.setBuddy(self.MAX_SPEED)
        self.label_9.setBuddy(self.ACC)
        self.label_10.setBuddy(self.DEC)
        self.label_28.setBuddy(self.FS_SPD)
        self.label_19.setBuddy(self.spiCommand)

        self.retranslateUi(MainWindow)
        self.turretMode.setCurrentIndex(1)
        self.skyMode.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        self.OC_SD.setCurrentIndex(1)
        self.POW_SR.setCurrentIndex(1)
        self.EXT_CLK.setCurrentIndex(1)
        self.F_PWM_DEC.setCurrentIndex(3)
        self.F_PWM_INT.setCurrentIndex(1)
        self.EXT_CLK.activated['QString'].connect(MainWindow.extClk)
        self.STEP_MODE.activated['QString'].connect(MainWindow.stepMode)
        self.MIN_SPEED.valueChanged['double'].connect(MainWindow.minSpeed)
        self.maxLon.textChanged['QString'].connect(MainWindow.maxLon)
        self.altinput.textChanged['QString'].connect(MainWindow.currentAlt)
        self.F_PWM_DEC.activated['QString'].connect(MainWindow.fPwmDec)
        self.timeEdit_2.timeChanged['QTime'].connect(MainWindow.timeInput)
        self.starInput.textChanged['QString'].connect(MainWindow.starInput)
        self.updateButton.clicked.connect(MainWindow.updateButtonClicked)
        self.timeEdit_1.timeChanged['QTime'].connect(MainWindow.timeInput)
        self.FS_SPD.valueChanged['double'].connect(MainWindow.fsSpeed)
        self.STALL_TH.valueChanged['double'].connect(MainWindow.stallTh)
        self.spiCommand.textChanged['QString'].connect(MainWindow.spiCommand)
        self.objectInput.textChanged['QString'].connect(MainWindow.objectInput)
        self.stopButton.clicked.connect(MainWindow.stopButtonClicked)
        self.timeEdit.timeChanged['QTime'].connect(MainWindow.timeInput)
        self.maxLat.textChanged['QString'].connect(MainWindow.maxLat)
        self.sendButton.clicked.connect(MainWindow.sendButtonClicked)
        self.restoreDefaultsButton.clicked.connect(MainWindow.restoreDefaultsButtonClicked)
        self.copyDeviceButton.clicked.connect(MainWindow.copyDriversButtonClicked)
        self.updateSettingsButton.clicked.connect(MainWindow.updateSettingsButtonClicked)
        self.OC_SD.activated['QString'].connect(MainWindow.ocSd)
        self.refreshButton.clicked.connect(MainWindow.refreshButtonClicked)
        self.skyMode.tabBarClicked['int'].connect(MainWindow.skyMode)
        self.calibrateButton.clicked.connect(MainWindow.calibrateButtonClicked)
        self.homeButton.clicked.connect(MainWindow.homeButtonClicked)
        self.fireButton.clicked.connect(MainWindow.fireButtonClicked)
        self.powerOffButton.clicked.connect(MainWindow.powerOffButtonClicked)
        self.timeMode.activated['QString'].connect(MainWindow.timeMode)
        self.timeMode_1.activated['QString'].connect(MainWindow.timeMode)
        self.timeMode_2.activated['QString'].connect(MainWindow.timeMode)
        self.manualOverride_1.clicked['bool'].connect(MainWindow.manualOverride)
        self.manualOverride.clicked['bool'].connect(MainWindow.manualOverride)
        self.manualOverride_2.clicked['bool'].connect(MainWindow.manualOverride)
        self.turretMode.currentChanged['int'].connect(MainWindow.turretMode)
        self.OCD_TH.valueChanged['double'].connect(MainWindow.ocdTh)
        self.F_PWM_INT.activated['QString'].connect(MainWindow.fPwmInt)
        self.satelliteInput.textChanged['QString'].connect(MainWindow.satelliteInput)
        self.POW_SR.activated['QString'].connect(MainWindow.powSr)
        self.SW_MODE.activated['QString'].connect(MainWindow.swMode)
        self.minLat.textChanged['QString'].connect(MainWindow.minLat)
        self.minLon.textChanged['QString'].connect(MainWindow.minLon)
        self.ACC.valueChanged['double'].connect(MainWindow.acc)
        self.DEC.valueChanged['double'].connect(MainWindow.dec)
        self.latInput.textChanged['QString'].connect(MainWindow.currentLat)
        self.MAX_SPEED.valueChanged['double'].connect(MainWindow.maxSpeed)
        self.EN_VSCOMP.activated['QString'].connect(MainWindow.enVscomp)
        self.lonInput.textChanged['QString'].connect(MainWindow.currentLon)
        self.OSC_SEL.activated['QString'].connect(MainWindow.oscSel)
        self.spiCommand.returnPressed.connect(MainWindow.sendButtonClicked)
        self.actionClose_Window.triggered.connect(MainWindow.closeWindow)
        self.actionSave_Defaults.triggered.connect(MainWindow.saveDefaults)
        self.actionCalibrate_2.triggered.connect(MainWindow.calibrateButtonClicked)
        self.actionHome_2.triggered.connect(MainWindow.homeButtonClicked)
        self.actionFire.triggered.connect(MainWindow.fireButtonClicked)
        self.actionPower_Off_2.triggered.connect(MainWindow.powerOffButtonClicked)
        self.actionEmergency_Stop.triggered.connect(MainWindow.stopButtonClicked)
        self.altTarget.textEdited['QString'].connect(MainWindow.altOut)
        self.azTarget.textEdited['QString'].connect(MainWindow.azOut)
        self.satelliteList.clicked['QModelIndex'].connect(MainWindow.satelliteList)
        self.objectList.clicked['QModelIndex'].connect(MainWindow.objectList)
        self.starList.clicked['QModelIndex'].connect(MainWindow.starList)
        self.mosquitoSize.valueChanged['double'].connect(MainWindow.mosquitoSize)
        self.callsignInput.textChanged['QString'].connect(MainWindow.callsignInput)
        self.airTrafficList.clicked['QModelIndex'].connect(MainWindow.airTraffic)
        self.actionReset_Defaults.triggered.connect(MainWindow.resetDefaults)
        self.speedMode.activated['int'].connect(MainWindow.speedMode)
        self.actionClose_Window.triggered.connect(MainWindow.close)
        self.cameraCalibrateButton.clicked.connect(MainWindow.cameraCalibrateButtonClicked)
        self.verticalSlider.valueChanged['int'].connect(MainWindow.hsvRedMinH)
        self.verticalSlider_2.valueChanged['int'].connect(MainWindow.hsvRedMinS)
        self.verticalSlider_3.valueChanged['int'].connect(MainWindow.hsvRedMinV)
        self.verticalSlider_4.valueChanged['int'].connect(MainWindow.hsvRedMaxH)
        self.verticalSlider_5.valueChanged['int'].connect(MainWindow.hsvRedMaxS)
        self.verticalSlider_6.valueChanged['int'].connect(MainWindow.hsvRedMaxV)
        self.verticalSlider_7.valueChanged['int'].connect(MainWindow.hsvGreenMinH)
        self.verticalSlider_8.valueChanged['int'].connect(MainWindow.hsvGreenMinS)
        self.verticalSlider_9.valueChanged['int'].connect(MainWindow.hsvGreenMinV)
        self.verticalSlider_10.valueChanged['int'].connect(MainWindow.hsvGreenMaxH)
        self.verticalSlider_11.valueChanged['int'].connect(MainWindow.hsvGreenMaxS)
        self.verticalSlider_12.valueChanged['int'].connect(MainWindow.hsvGreenMaxV)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.turretMode, self.verticalSlider)
        MainWindow.setTabOrder(self.verticalSlider, self.verticalSlider_2)
        MainWindow.setTabOrder(self.verticalSlider_2, self.verticalSlider_3)
        MainWindow.setTabOrder(self.verticalSlider_3, self.verticalSlider_4)
        MainWindow.setTabOrder(self.verticalSlider_4, self.verticalSlider_5)
        MainWindow.setTabOrder(self.verticalSlider_5, self.verticalSlider_6)
        MainWindow.setTabOrder(self.verticalSlider_6, self.verticalSlider_7)
        MainWindow.setTabOrder(self.verticalSlider_7, self.verticalSlider_8)
        MainWindow.setTabOrder(self.verticalSlider_8, self.verticalSlider_9)
        MainWindow.setTabOrder(self.verticalSlider_9, self.verticalSlider_10)
        MainWindow.setTabOrder(self.verticalSlider_10, self.verticalSlider_11)
        MainWindow.setTabOrder(self.verticalSlider_11, self.verticalSlider_12)
        MainWindow.setTabOrder(self.verticalSlider_12, self.scrollArea_2)
        MainWindow.setTabOrder(self.scrollArea_2, self.manualOverride_1)
        MainWindow.setTabOrder(self.manualOverride_1, self.latInput)
        MainWindow.setTabOrder(self.latInput, self.lonInput)
        MainWindow.setTabOrder(self.lonInput, self.altinput)
        MainWindow.setTabOrder(self.altinput, self.skyMode)
        MainWindow.setTabOrder(self.skyMode, self.timeMode)
        MainWindow.setTabOrder(self.timeMode, self.timeEdit)
        MainWindow.setTabOrder(self.timeEdit, self.starInput)
        MainWindow.setTabOrder(self.starInput, self.starList)
        MainWindow.setTabOrder(self.starList, self.timeMode_1)
        MainWindow.setTabOrder(self.timeMode_1, self.timeEdit_1)
        MainWindow.setTabOrder(self.timeEdit_1, self.objectInput)
        MainWindow.setTabOrder(self.objectInput, self.objectList)
        MainWindow.setTabOrder(self.objectList, self.timeMode_2)
        MainWindow.setTabOrder(self.timeMode_2, self.timeEdit_2)
        MainWindow.setTabOrder(self.timeEdit_2, self.satelliteInput)
        MainWindow.setTabOrder(self.satelliteInput, self.airTrafficList)
        MainWindow.setTabOrder(self.airTrafficList, self.refreshButton)
        MainWindow.setTabOrder(self.refreshButton, self.minLat)
        MainWindow.setTabOrder(self.minLat, self.minLon)
        MainWindow.setTabOrder(self.minLon, self.maxLat)
        MainWindow.setTabOrder(self.maxLat, self.maxLon)
        MainWindow.setTabOrder(self.maxLon, self.manualOverride_2)
        MainWindow.setTabOrder(self.manualOverride_2, self.mosquitoSize)
        MainWindow.setTabOrder(self.mosquitoSize, self.updateButton)
        MainWindow.setTabOrder(self.updateButton, self.calibrateButton)
        MainWindow.setTabOrder(self.calibrateButton, self.homeButton)
        MainWindow.setTabOrder(self.homeButton, self.fireButton)
        MainWindow.setTabOrder(self.fireButton, self.powerOffButton)
        MainWindow.setTabOrder(self.powerOffButton, self.stopButton)
        MainWindow.setTabOrder(self.stopButton, self.MAX_SPEED)
        MainWindow.setTabOrder(self.MAX_SPEED, self.MIN_SPEED)
        MainWindow.setTabOrder(self.MIN_SPEED, self.ACC)
        MainWindow.setTabOrder(self.ACC, self.DEC)
        MainWindow.setTabOrder(self.DEC, self.FS_SPD)
        MainWindow.setTabOrder(self.FS_SPD, self.OCD_TH)
        MainWindow.setTabOrder(self.OCD_TH, self.STALL_TH)
        MainWindow.setTabOrder(self.STALL_TH, self.STEP_MODE)
        MainWindow.setTabOrder(self.STEP_MODE, self.OSC_SEL)
        MainWindow.setTabOrder(self.OSC_SEL, self.EXT_CLK)
        MainWindow.setTabOrder(self.EXT_CLK, self.SW_MODE)
        MainWindow.setTabOrder(self.SW_MODE, self.EN_VSCOMP)
        MainWindow.setTabOrder(self.EN_VSCOMP, self.OC_SD)
        MainWindow.setTabOrder(self.OC_SD, self.POW_SR)
        MainWindow.setTabOrder(self.POW_SR, self.F_PWM_DEC)
        MainWindow.setTabOrder(self.F_PWM_DEC, self.F_PWM_INT)
        MainWindow.setTabOrder(self.F_PWM_INT, self.updateSettingsButton)
        MainWindow.setTabOrder(self.updateSettingsButton, self.copyDeviceButton)
        MainWindow.setTabOrder(self.copyDeviceButton, self.restoreDefaultsButton)
        MainWindow.setTabOrder(self.restoreDefaultsButton, self.spiCommand)
        MainWindow.setTabOrder(self.spiCommand, self.sendButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Open Turret Dashboard"))
        self.label_5.setText(_translate("MainWindow", "Configuration"))
        self.label_55.setText(_translate("MainWindow", "Speed Mode:"))
        self.speedMode.setStatusTip(_translate("MainWindow", "Set Speed Mode of Turret"))
        self.speedMode.setItemText(0, _translate("MainWindow", "Slow"))
        self.speedMode.setItemText(1, _translate("MainWindow", "Medium"))
        self.speedMode.setItemText(2, _translate("MainWindow", "Fast"))
        self.turretMode.setTabText(self.turretMode.indexOf(self.manual), _translate("MainWindow", "Manual"))
        self.manualOverride.setStatusTip(_translate("MainWindow", "Enable Manual Joystick Override"))
        self.manualOverride.setText(_translate("MainWindow", "Manual Override"))
        self.cameraCalibrateButton.setText(_translate("MainWindow", "Camera Calibration"))
        self.label_51.setText(_translate("MainWindow", "Red Min"))
        self.label_38.setText(_translate("MainWindow", "Red Max"))
        self.label_52.setText(_translate("MainWindow", "Green Min"))
        self.label_53.setText(_translate("MainWindow", "Green Max"))
        self.label_41.setText(_translate("MainWindow", "S"))
        self.label_47.setText(_translate("MainWindow", "V"))
        self.label_45.setText(_translate("MainWindow", "H"))
        self.label_50.setText(_translate("MainWindow", "V"))
        self.label_40.setText(_translate("MainWindow", "H"))
        self.label_43.setText(_translate("MainWindow", "V"))
        self.label_48.setText(_translate("MainWindow", "H"))
        self.label_44.setText(_translate("MainWindow", "V"))
        self.label_42.setText(_translate("MainWindow", "S"))
        self.label_46.setText(_translate("MainWindow", "S"))
        self.label_39.setText(_translate("MainWindow", "H"))
        self.label_49.setText(_translate("MainWindow", "S"))
        self.turretMode.setTabText(self.turretMode.indexOf(self.tab_2), _translate("MainWindow", "Laser"))
        self.manualOverride_1.setStatusTip(_translate("MainWindow", "Enable Manual Joystick Override"))
        self.manualOverride_1.setText(_translate("MainWindow", "Manual Override"))
        self.latInput.setStatusTip(_translate("MainWindow", "Set Current GPS Latitude in Decimal"))
        self.latInput.setPlaceholderText(_translate("MainWindow", "latitude"))
        self.label_4.setText(_translate("MainWindow", "Current Longitude:"))
        self.lonInput.setStatusTip(_translate("MainWindow", "Set Current GPS Longitude in Decimal"))
        self.lonInput.setPlaceholderText(_translate("MainWindow", "longitude"))
        self.label_3.setText(_translate("MainWindow", "Current Latitude:"))
        self.label_57.setText(_translate("MainWindow", "Current Altitude:"))
        self.altinput.setStatusTip(_translate("MainWindow", "Set Current GPS Altitude in Meters"))
        self.altinput.setPlaceholderText(_translate("MainWindow", "altitude"))
        self.label_22.setText(_translate("MainWindow", "Time Mode:"))
        self.timeMode.setStatusTip(_translate("MainWindow", "Select Time Mode"))
        self.timeMode.setItemText(0, _translate("MainWindow", "Current"))
        self.timeMode.setItemText(1, _translate("MainWindow", "Custom"))
        self.label_29.setText(_translate("MainWindow", "Time:"))
        self.starInput.setStatusTip(_translate("MainWindow", "Enter Star Code to Track"))
        self.starInput.setPlaceholderText(_translate("MainWindow", "star code"))
        self.label_36.setText(_translate("MainWindow", "Star:"))
        self.starList.setStatusTip(_translate("MainWindow", "List of some Available Stars"))
        self.skyMode.setTabText(self.skyMode.indexOf(self.tab_4), _translate("MainWindow", "Star"))
        self.label_30.setText(_translate("MainWindow", "Time Mode:"))
        self.timeMode_1.setStatusTip(_translate("MainWindow", "Select Time Mode"))
        self.timeMode_1.setItemText(0, _translate("MainWindow", "Current"))
        self.timeMode_1.setItemText(1, _translate("MainWindow", "Custom"))
        self.label_31.setText(_translate("MainWindow", "Time:"))
        self.label_56.setText(_translate("MainWindow", "Solar Object:"))
        self.objectInput.setStatusTip(_translate("MainWindow", "Enter Solar Object Name to Track"))
        self.objectInput.setPlaceholderText(_translate("MainWindow", "solar object name"))
        self.objectList.setStatusTip(_translate("MainWindow", "List of Solar System Entities"))
        self.skyMode.setTabText(self.skyMode.indexOf(self.tab_5), _translate("MainWindow", "Solar System"))
        self.label_14.setText(_translate("MainWindow", "Time Mode:"))
        self.timeMode_2.setStatusTip(_translate("MainWindow", "Select Time Mode"))
        self.timeMode_2.setItemText(0, _translate("MainWindow", "Current"))
        self.timeMode_2.setItemText(1, _translate("MainWindow", "Custom"))
        self.label_13.setText(_translate("MainWindow", "Time:"))
        self.label_37.setText(_translate("MainWindow", "Satellite:"))
        self.satelliteInput.setStatusTip(_translate("MainWindow", "Enter Sattelite Name to Track"))
        self.satelliteInput.setPlaceholderText(_translate("MainWindow", "satellite name"))
        self.satelliteList.setStatusTip(_translate("MainWindow", "List of Active Sattelites"))
        self.skyMode.setTabText(self.skyMode.indexOf(self.tab_6), _translate("MainWindow", "Satellite"))
        self.label.setText(_translate("MainWindow", "Select Air Traffic:"))
        self.callsignInput.setStatusTip(_translate("MainWindow", "Enter Callsign to Track"))
        self.callsignInput.setPlaceholderText(_translate("MainWindow", "callsign"))
        self.airTrafficList.setStatusTip(_translate("MainWindow", "List of Available Air Traffic"))
        self.refreshButton.setStatusTip(_translate("MainWindow", "Refresh Air Traffic List"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh Traffic"))
        self.label_32.setText(_translate("MainWindow", "Min Latitude:"))
        self.minLat.setStatusTip(_translate("MainWindow", "GPS Latitude in Decimal"))
        self.minLat.setPlaceholderText(_translate("MainWindow", "latitude"))
        self.label_33.setText(_translate("MainWindow", "Min Longitude:"))
        self.minLon.setStatusTip(_translate("MainWindow", "GPS Longitude in Decimal"))
        self.minLon.setPlaceholderText(_translate("MainWindow", "longitude"))
        self.label_34.setText(_translate("MainWindow", "Max Latitude:"))
        self.maxLat.setStatusTip(_translate("MainWindow", "GPS Latitude in Decimal"))
        self.maxLat.setPlaceholderText(_translate("MainWindow", "latitude"))
        self.label_35.setText(_translate("MainWindow", "Max Longitude:"))
        self.maxLon.setStatusTip(_translate("MainWindow", "GPS Longitude in Decimal"))
        self.maxLon.setPlaceholderText(_translate("MainWindow", "longitude"))
        self.skyMode.setTabText(self.skyMode.indexOf(self.tab_7), _translate("MainWindow", "Air Traffic"))
        self.turretMode.setTabText(self.turretMode.indexOf(self.tab_3), _translate("MainWindow", "Sky"))
        self.manualOverride_2.setStatusTip(_translate("MainWindow", "Enable Manual Joystick Override"))
        self.manualOverride_2.setText(_translate("MainWindow", "Manual Override"))
        self.label_54.setText(_translate("MainWindow", "Mosquito Size:"))
        self.mosquitoSize.setStatusTip(_translate("MainWindow", "Set Mosquito Size"))
        self.turretMode.setTabText(self.turretMode.indexOf(self.tab), _translate("MainWindow", "Mosquito"))
        self.updateButton.setStatusTip(_translate("MainWindow", "Update Motor Drivers with Latest Controls"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.label_6.setText(_translate("MainWindow", "Actions"))
        self.calibrateButton.setStatusTip(_translate("MainWindow", "Calibrate: Set Current Location to Home"))
        self.calibrateButton.setText(_translate("MainWindow", "Calibrate"))
        self.homeButton.setStatusTip(_translate("MainWindow", "Home Motor Drivers"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.fireButton.setStatusTip(_translate("MainWindow", "Home Motor Drivers"))
        self.fireButton.setText(_translate("MainWindow", "Fire"))
        self.powerOffButton.setStatusTip(_translate("MainWindow", "Power Off Motor Drivers"))
        self.powerOffButton.setText(_translate("MainWindow", "Power Off"))
        self.stopButton.setStatusTip(_translate("MainWindow", "Force Stop in case of Emergencies"))
        self.stopButton.setText(_translate("MainWindow", "EMERGENCY STOP"))
        self.label_59.setText(_translate("MainWindow", "Target Position"))
        self.label_58.setText(_translate("MainWindow", "Altitude:"))
        self.label_60.setText(_translate("MainWindow", "Azimuth:"))
        self.altTarget.setStatusTip(_translate("MainWindow", "Target Altitude"))
        self.azTarget.setStatusTip(_translate("MainWindow", "Target Azimuth"))
        self.label_64.setText(_translate("MainWindow", "Distance:"))
        self.distanceTarget.setStatusTip(_translate("MainWindow", "Distance to Target"))
        self.label_63.setText(_translate("MainWindow", "Actual Position"))
        self.label_61.setText(_translate("MainWindow", "Altitude:"))
        self.altActual.setStatusTip(_translate("MainWindow", "Current Altitude"))
        self.label_62.setText(_translate("MainWindow", "Azimuth:"))
        self.azActual.setStatusTip(_translate("MainWindow", "Current Azimuth"))
        self.label_8.setText(_translate("MainWindow", "Settings"))
        self.label_11.setText(_translate("MainWindow", "MinSpeed (step/s):"))
        self.label_12.setText(_translate("MainWindow", "OCD TH (A):"))
        self.label_15.setText(_translate("MainWindow", "Stall TH (A):"))
        self.label_16.setText(_translate("MainWindow", "Step Mode (1/):"))
        self.STEP_MODE.setItemText(0, _translate("MainWindow", "128"))
        self.STEP_MODE.setItemText(1, _translate("MainWindow", "64"))
        self.STEP_MODE.setItemText(2, _translate("MainWindow", "32"))
        self.STEP_MODE.setItemText(3, _translate("MainWindow", "16"))
        self.STEP_MODE.setItemText(4, _translate("MainWindow", "8"))
        self.STEP_MODE.setItemText(5, _translate("MainWindow", "4"))
        self.STEP_MODE.setItemText(6, _translate("MainWindow", "2"))
        self.STEP_MODE.setItemText(7, _translate("MainWindow", "1"))
        self.label_17.setText(_translate("MainWindow", "SW_MODE:"))
        self.label_18.setText(_translate("MainWindow", "OC_SD:"))
        self.OC_SD.setItemText(0, _translate("MainWindow", "0"))
        self.OC_SD.setItemText(1, _translate("MainWindow", "1"))
        self.SW_MODE.setItemText(0, _translate("MainWindow", "0"))
        self.SW_MODE.setItemText(1, _translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", "POW_SR (V/us):"))
        self.POW_SR.setItemText(0, _translate("MainWindow", "75"))
        self.POW_SR.setItemText(1, _translate("MainWindow", "110"))
        self.POW_SR.setItemText(2, _translate("MainWindow", "260"))
        self.POW_SR.setItemText(3, _translate("MainWindow", "320"))
        self.label_23.setText(_translate("MainWindow", "CONFIG"))
        self.label_24.setText(_translate("MainWindow", "OSC_SEL:"))
        self.OSC_SEL.setItemText(0, _translate("MainWindow", "000"))
        self.OSC_SEL.setItemText(1, _translate("MainWindow", "001"))
        self.OSC_SEL.setItemText(2, _translate("MainWindow", "010"))
        self.OSC_SEL.setItemText(3, _translate("MainWindow", "011"))
        self.OSC_SEL.setItemText(4, _translate("MainWindow", "100"))
        self.OSC_SEL.setItemText(5, _translate("MainWindow", "101"))
        self.OSC_SEL.setItemText(6, _translate("MainWindow", "110"))
        self.OSC_SEL.setItemText(7, _translate("MainWindow", "111"))
        self.label_25.setText(_translate("MainWindow", "EXT_CLK:"))
        self.EXT_CLK.setItemText(0, _translate("MainWindow", "0"))
        self.EXT_CLK.setItemText(1, _translate("MainWindow", "1"))
        self.label_21.setText(_translate("MainWindow", "EN_VSCOMP"))
        self.EN_VSCOMP.setItemText(0, _translate("MainWindow", "0"))
        self.EN_VSCOMP.setItemText(1, _translate("MainWindow", "1"))
        self.label_26.setText(_translate("MainWindow", "F_PWM_DEC:"))
        self.label_27.setText(_translate("MainWindow", "F_PWM_INT:"))
        self.F_PWM_DEC.setItemText(0, _translate("MainWindow", "000"))
        self.F_PWM_DEC.setItemText(1, _translate("MainWindow", "001"))
        self.F_PWM_DEC.setItemText(2, _translate("MainWindow", "010"))
        self.F_PWM_DEC.setItemText(3, _translate("MainWindow", "011"))
        self.F_PWM_DEC.setItemText(4, _translate("MainWindow", "100"))
        self.F_PWM_DEC.setItemText(5, _translate("MainWindow", "101"))
        self.F_PWM_DEC.setItemText(6, _translate("MainWindow", "110"))
        self.F_PWM_DEC.setItemText(7, _translate("MainWindow", "111"))
        self.F_PWM_INT.setItemText(0, _translate("MainWindow", "000"))
        self.F_PWM_INT.setItemText(1, _translate("MainWindow", "001"))
        self.F_PWM_INT.setItemText(2, _translate("MainWindow", "010"))
        self.F_PWM_INT.setItemText(3, _translate("MainWindow", "011"))
        self.F_PWM_INT.setItemText(4, _translate("MainWindow", "100"))
        self.F_PWM_INT.setItemText(5, _translate("MainWindow", "101"))
        self.F_PWM_INT.setItemText(6, _translate("MainWindow", "110"))
        self.F_PWM_INT.setItemText(7, _translate("MainWindow", "111"))
        self.label_7.setText(_translate("MainWindow", "MaxSpeed (step/s):"))
        self.label_9.setText(_translate("MainWindow", "Accel (step/s^2):"))
        self.label_10.setText(_translate("MainWindow", "Decel (step/s^2):"))
        self.label_28.setText(_translate("MainWindow", "FS Speed (step/s):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Pan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Tilt"))
        self.label_2.setText(_translate("MainWindow", "Rset Value:"))
        self.doubleSpinBox_3.setSuffix(_translate("MainWindow", "kOhm"))
        self.label_65.setText(_translate("MainWindow", "Torch Current:"))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", "mA"))
        self.label_66.setText(_translate("MainWindow", "Flash Current:"))
        self.doubleSpinBox_2.setSuffix(_translate("MainWindow", "mA"))
        self.label_67.setText(_translate("MainWindow", "Safety Timer (ms):"))
        self.comboBox.setItemText(0, _translate("MainWindow", "50"))
        self.comboBox.setItemText(1, _translate("MainWindow", "100"))
        self.comboBox.setItemText(2, _translate("MainWindow", "200"))
        self.comboBox.setItemText(3, _translate("MainWindow", "300"))
        self.comboBox.setItemText(4, _translate("MainWindow", "400"))
        self.comboBox.setItemText(5, _translate("MainWindow", "500"))
        self.comboBox.setItemText(6, _translate("MainWindow", "600"))
        self.comboBox.setItemText(7, _translate("MainWindow", "700"))
        self.comboBox.setItemText(8, _translate("MainWindow", "800"))
        self.comboBox.setItemText(9, _translate("MainWindow", "900"))
        self.comboBox.setItemText(10, _translate("MainWindow", "1000"))
        self.comboBox.setItemText(11, _translate("MainWindow", "1100"))
        self.comboBox.setItemText(12, _translate("MainWindow", "1200"))
        self.comboBox.setItemText(13, _translate("MainWindow", "1300"))
        self.comboBox.setItemText(14, _translate("MainWindow", "1400"))
        self.comboBox.setItemText(15, _translate("MainWindow", "3200"))
        self.label_68.setText(_translate("MainWindow", "Current Step (us):"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "25"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "50"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "100"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "200"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Laser"))
        self.updateSettingsButton.setStatusTip(_translate("MainWindow", "Update Driver Settings"))
        self.updateSettingsButton.setText(_translate("MainWindow", "Update Settings"))
        self.copyDeviceButton.setStatusTip(_translate("MainWindow", "Copy Current Values from Motor Drivers"))
        self.copyDeviceButton.setText(_translate("MainWindow", "Copy Current"))
        self.restoreDefaultsButton.setStatusTip(_translate("MainWindow", "Restore Default Driver Values"))
        self.restoreDefaultsButton.setText(_translate("MainWindow", "Restore Defaults"))
        self.label_19.setText(_translate("MainWindow", "SPI Command:"))
        self.spiCommand.setStatusTip(_translate("MainWindow", "Enter Bare SPI Command to Send"))
        self.sendButton.setStatusTip(_translate("MainWindow", "Send SPI Command to Drivers"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.menuSettings.setTitle(_translate("MainWindow", "File"))
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_Defaults.setText(_translate("MainWindow", "Save Defaults"))
        self.actionSave_Defaults.setShortcut(_translate("MainWindow", "Meta+S"))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionPower_Off.setText(_translate("MainWindow", "Power Off"))
        self.actionForce_Stop.setText(_translate("MainWindow", "Force Stop"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionCalibrate_2.setText(_translate("MainWindow", "Calibrate"))
        self.actionHome_2.setText(_translate("MainWindow", "Home"))
        self.actionFire.setText(_translate("MainWindow", "Fire"))
        self.actionPower_Off_2.setText(_translate("MainWindow", "Power Off"))
        self.actionEmergency_Stop.setText(_translate("MainWindow", "Emergency Stop"))
        self.actionEmergency_Stop.setShortcut(_translate("MainWindow", "Meta+C"))
        self.actionClose_Window.setText(_translate("MainWindow", "Close Window"))
        self.actionClose_Window.setShortcut(_translate("MainWindow", "Meta+W"))
        self.actionReset_Defaults.setText(_translate("MainWindow", "Reset Defaults"))
